website/goals/urls.py
from coffin.conf.urls import *
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy

admin.autodiscover()

from goals import views

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^password_reset$', 'goals.views.password_reset', kwargs={'template_name': 'password_reset_form.jinja', 'post_reset_redirect': reverse_lazy('password_reset_done'), 'email_template_name': 'password_reset_email.html'}, name="password_reset"),
    url(r'^password_reset/done$', 'goals.views.password_reset_done', name="password_reset_done"),
    url(r'^reset(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', kwargs={'template_name': 'password_reset_confirm.html'}),
    url(r'^reset/done$', 'django.contrib.auth.views.password_reset_complete', kwargs={'template_name': 'password_reset_complete.html'}),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.goals, name="home"),
    url(r'^analytics/$', views.analytics, name="analytics"),
    url(r'^totals/$', views.totals, name="totals"),
    url(r'^github/$', views.github, name="github"),

    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^signup/$', views.signup, name="signup"),

    # API
    url(r'^api/check$', views.api_check),
    url(r'^api/goal_edit$', views.api_goal_edit),
    url(r'^api/goal_new$', views.api_goal_new),
    url(r'^api/goal_delete$', views.api_goal_delete),

    #url(r'', include('social_auth.urls')),
)

website/goals/models.py
from django.db import models
from django.contrib.auth.models import User

from dateutil.relativedelta import relativedelta
import redis

import datetime
import re

class Goal(models.Model):
    FREQ_DAILY = 1
    FREQ_WEEKLY = 2
    FREQ_MONTHLY = 3
    FREQ_YEARLY = 4
    FREQ_CHOICES = (
            (FREQ_DAILY, "daily"),
            (FREQ_WEEKLY, "weekly"),
            (FREQ_MONTHLY, "monthly"),
            (FREQ_YEARLY, "yearly"),
            )

    name = models.TextField()
    frequency = models.IntegerField(choices=FREQ_CHOICES)
    user = models.ForeignKey(User)

    redis = redis.StrictRedis(host='localhost', port=15126, db=0)

    def massage_date(self, date):
        if isinstance(date, datetime.date):
            date = date.strftime("%Y-%m-%d")
        assert re.match("^\d{4}-\d{2}-\d{2}$", date)
        return date

    def get_goal_key(self):
        return "user:%s:goal:%s" % (self.user_id, self.id)

    def get_date_key(self, date):
        date_str = self.massage_date(date)
        key = "%s:%s" % (self.get_goal_key(), date_str)
        return key

    def get_date_count(self, date):
        key = self.get_date_key(date)
        count = int(self.redis.get(key) or 0)
        return count

    def incr(self, date, incr):
        return self.redis.incr(self.get_date_key(date), incr)

    def get_trailing_dates(self, for_date=None):
        if for_date is None:
            for_date = datetime.date.today()

        delta = datetime.timedelta(days=1)
        if self.frequency == self.FREQ_WEEKLY:
            while for_date.isoweekday() > 1:
                for_date -= datetime.timedelta(days=1)
            delta = delta * 7
        elif self.frequency == self.FREQ_MONTHLY:
            for_date = datetime.date(for_date.year, for_date.month, 1)
            delta = relativedelta(months=1)
        elif self.frequency == self.FREQ_YEARLY:
            for_date = datetime.date(for_date.year, 1, 1)
            delta = relativedelta(years=1)

        results = [for_date - delta * x for x in range(6, -1, -1)]
        return results

website/goals/forms.py
from django import forms
from django.template import loader
from django.utils.http import int_to_base36
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.conf import settings

from django.utils.translation import ugettext, ugettext_lazy as _

class PasswordResetForm(forms.Form):
    error_messages = {
        'unknown': _("That e-mail address doesn't have an associated "
                     "user account. Are you sure you've registered?"),
        'unusable': _("The user account associated with this e-mail "
                      "address cannot reset the password."),
    }
    email = forms.EmailField(label=_("E-mail"), max_length=75)

    def clean_email(self):
        """
        Validates that an active user exists with the given email address.
        """
        email = self.cleaned_data["email"]
        self.users_cache = User.objects.filter(email__iexact=email,
                                               is_active=True)
        if not len(self.users_cache):
            raise forms.ValidationError(self.error_messages['unknown'])
        if any(user.has_unusable_password() for user in self.users_cache):
            raise forms.ValidationError(self.error_messages['unusable'])
        return email

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        for user in self.users_cache:
            c = {
                'email': user.email,
                'domain': settings.WEBSITE_URL,
                'site_name': settings.WEBSITE_NAME,
                'uid': int_to_base36(user.id),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': settings.WEBSITE_URL.split("://")[0],
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            user.email_user(subject, email)

website/goals/views.py
from coffin.shortcuts import render_to_response
from django.contrib.auth import authenticate, logout as logout_user, login as login_user
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.utils.html import simple_email_re as email_re
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt

from goals.models import Goal, User

import cjson
import datetime
import random
import re

def r2r(template, request, data=None):
    if data is None:
        data = {}
    data['request'] = request
    return render_to_response(template, data, context_instance=RequestContext(request))

def goals(request):
    if request.user.is_authenticated():
        goals = request.user.goal_set.order_by('frequency')
    else:
        goals = [
                Goal(name="Exercise", frequency=Goal.FREQ_DAILY),
                Goal(name="Meditate", frequency=Goal.FREQ_DAILY),
                Goal(name="Floss", frequency=Goal.FREQ_WEEKLY),
                Goal(name="Read", frequency=Goal.FREQ_WEEKLY),
                Goal(name="Blog", frequency=Goal.FREQ_MONTHLY),
        ]
        for goal in goals:
            goal.get_date_count = lambda d: random.randint(0, 2)

    return r2r("index.jinja", request, {"goals": goals})

def totals(request):
    totals = []
    if request.user.is_authenticated():
        r = Goal().redis
        pipe = r.pipeline()
        for k in r.keys():
            pipe.get(k)
        totals = [{'date': k, 'count': c} for k in r.keys() for c in pipe.execute()]
    return r2r("totals.jinja",request,{'totals':totals})

def analytics(request):
    users = set()
    for key in Goal.redis.keys("user:*:goal:*:{}".format((datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d"))):
        users.add(re.match("user:(\d+):", key).groups()[0])
    return JsonResponse({"unique_usergoals_yesterday": len(users)})

@csrf_exempt
def github(request):
    from django.conf import settings
    import subprocess
    subprocess.check_call(["git", "pull"], cwd=settings.WEBSITE_DIR)
    subprocess.check_call(["pbdeploy"], cwd=settings.WEBSITE_DIR)
    return HttpResponse()

def login(request):
    def failure(error_msg):
        return r2r("login.jinja", request, locals())

    if request.method == "GET":
        return r2r("login.jinja", request, locals())
    else:
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)
        if user is not None:
            if user.is_active:
                login_user(request, user)
                # Redirect to a success page.
                return redirect("home")
            else:
                # Return a 'disabled account' error message
                return failure("This account has been disabled.")
        else:
            # Return an 'invalid login' error message.
            return failure("Invalid email address or password.")

def logout(request):
    logout_user(request)
    return redirect("home")

def signup(request):
    if request.method == "GET":
        return r2r("signup.jinja", request, locals())
    else:
        email = request.POST['email']
        password = request.POST['password']
        if not email_re.match(email):
            error_msg = "Please enter a valid email address."
            return r2r("signup.jinja", request, locals())
        if len(password) < 6:
            error_msg = "Please enter a password of at least 6 characters."
            return r2r("signup.jinja", request, locals())
        if User.objects.filter(username=email).count():
            error_msg = "An account with this email address already exists."
            return r2r("signup.jinja", request, locals())

        user = User.objects.create_user(email, password=password)
        user.save()
        user = authenticate(username=email, password=password)
        login_user(request, user)
        return redirect("home")

def api_goal_delete(request):
    if not request.user.is_authenticated(): return {"logged_out": True}
    goal_id = int(request.GET['goal'])

    if not Goal.objects.filter(id=goal_id, user__id=request.user.id).count():
        raise Exception("401 Unauthorized")

    Goal.objects.filter(id=goal_id).delete()
    return JsonResponse({})

def api_goal_edit(request):
    if not request.user.is_authenticated(): return {"logged_out": True}
    goal_id = int(request.GET['goal'])
    goal_name = request.GET['name']

    if not Goal.objects.filter(id=goal_id, user__id=request.user.id).count():
        raise Exception("401 Unauthorized")

    Goal.objects.filter(id=goal_id).update(name=goal_name)
    return JsonResponse({})

def api_goal_new(request):
    if not request.user.is_authenticated(): return {"logged_out": True}
    goal_name = request.GET['name']
    goal_freq = request.GET['frequency']

    Goal(name=goal_name, frequency=goal_freq, user=request.user).save()
    return JsonResponse({})

def api_check(request):
    if not request.user.is_authenticated(): return {"logged_out": True}
    goal_id = request.GET['id']
    goal_date = request.GET['date']
    action = request.GET['action']

    if not Goal.objects.filter(id=goal_id, user__id=request.user.id).count():
        raise Exception("401 Unauthorized")

    incr = 1 if action == "increment" else -1
    Goal.objects.get(id=goal_id).incr(goal_date, incr)
    return JsonResponse({})

def password_reset(request, is_admin_site=False,
                   template_name='registration/password_reset_form.html',
                   email_template_name='registration/password_reset_email.html',
                   subject_template_name='registration/password_reset_subject.txt',
                   post_reset_redirect=None,
                   from_email=None,
                   extra_context=None):

    from goals.forms import PasswordResetForm as password_reset_form
    from django.contrib.auth.tokens import default_token_generator as token_generator

    if post_reset_redirect is None:
        post_reset_redirect = reverse('django.contrib.auth.views.password_reset_done')
    if request.method == "POST":
        form = password_reset_form(request.POST)
        if form.is_valid():
            opts = {
                'use_https': request.is_secure(),
                'token_generator': token_generator,
                'from_email': from_email,
                'email_template_name': email_template_name,
                'subject_template_name': subject_template_name,
                'request': request,
            }
            form.save(**opts)
            return redirect(post_reset_redirect)
    else:
        form = password_reset_form()
    context = { 'form': form }
    if extra_context is not None:
        context.update(extra_context)
    return r2r(template_name, request, context)

def password_reset_done(request):
    message = "We've e-mailed you your username and instructions for resetting your password to the e-mail address you submitted. You should be receiving it shortly."
    messages.success(request, message)
    return redirect('home')

website/goals/templates/base.jinja
{% load compress %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=800, initial-scale=1.0">
        {% block extra_meta %}{% endblock %}
        <title>Mike's Goals</title>

        {% compress css %}
            <link rel="stylesheet" type="text/css" href="/static/bootstrap-2.2.2/css/bootstrap.min.css" />
            <link rel="stylesheet" type="text/css" href="/static/bootstrap-2.2.2/css/bootstrap-responsive.min.css" />
            <link rel="stylesheet" type="text/css" href="/static/css/goals.css"/>
        {% endcompress %}
        {% compress css %}{% block extra_css %}{% endblock %}{% endcompress %}
        <link rel="icon" type="image/png" href="/static/img/accept.png" />

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. MUST BE BEFORE BODY -->
        <!--[if lt IE 9]>
            <script src="/static/js/html5.js"></script>
        <![endif]-->
        <script>
            var goals = {
                is_authenticated: {{ 'true' if request.user.is_authenticated() else 'false' }},
            }
        </script>
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <a href="https://github.com/mrooney/mikesgoals" target="_blank" class="visible-desktop"><img style="opacity: 0.15; position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
        <div class="container-narrow">
            <div class="masthead">
                <ul class="nav nav-pills pull-right">
                    <li><a href="{% url home %}">Home</a></li>
                    <li><a href="https://www.gittip.com/mrooney/">Donate</a></li>
                    {% if request.user.is_authenticated() %}
                        <li><a href="{% url logout %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url login %}">Login</a></li>
                    {% endif %}
                </ul>
                <h3 class="muted">
                    <a href="{% url home %}">Mike's Goals</a>
                </h3>
            </div>

            <div class="well">
                <div class="message-container">
                    {% for message in messages %}
                        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                            <a class="close" data-dismiss="alert" href="#">&times;</a>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
                {% block content %}{% endblock %}
            </div>
        </div>

        {% block after_container %}{% endblock %}

        {% compress js %}
            <script type="text/javascript" src="/static/js/jquery-1.7.2.min.js"></script>
            <script type="text/javascript" src="/static/js/goals.js"></script>
        {% endcompress %}
        {% block extra_js %}{% endblock %}
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-37419893-1']);
          _gaq.push(['_setDomainName', 'rowk.com']);
          _gaq.push(['_trackPageview']);
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </body>
</html>

website/goals/templates/index.jinja
{% extends "base.jinja" %}

{% block extra_meta %}
    <meta name="format-detection" content="telephone=no" />
{% endblock %}

{% macro render_date(date, frequency) -%}
    {% if frequency == 1 %}
        {{ date.strftime("%a") }}
    {% elif frequency == 2 %}
        {{ date.strftime("%m/%d") }}
    {% elif frequency == 3 %}
        {{ date.strftime("%b") }}
    {% elif frequency == 4 %}
        {{ date.strftime("%Y") }}
    {% else %}
        {{ date }}
    {% endif %}
{%- endmacro %}

{% block content %}
    {% if request.user.is_authenticated() %}
        <div class="clearfix">
            <div class="pull-left">Welcome back, {{ request.user }}!</div>
            <div class="pull-right">
                {% if goals %}<a href="#" class="newGoal"><i class="icon-plus"></i> New Goal</a>{% endif %}
            </div>
        </div>
        {% if not goals %}
            <div class="text-center"><h1><a href="#" class="newGoal">New Goal</a></h1></div>
        {% endif %}
    {% else %}
        <div class="jumbotron">
            <h2>Accomplish Your Goals!</h2>
            <p class="lead">Mike's Goals makes it simple to define your goals and track your progress.</p>
            <a class="btn btn-large btn-success" href="{% url signup %}">Sign up for free</a>
            <br/>or <a href="{% url login %}">login</a>
            {#{% if 'foursquare' in request.GET %}
                <a href="{% url socialauth_begin 'foursquare' %}">login with Foursquare</a>
            {% endif %}#}
        </div>
        <div class="demo-text text-success"><b>live demo</b>: click a box to add a check or click an existing check to remove it</div>
    {% endif %}
    <table id="trackerTable">
        {% set current_freq = 1 %}
        {% for goal in goals %}
            {% if goal.frequency != current_freq %}
                {% set current_freq = goal.frequency %}
                <tr><td></td><td class="frequency-header" colspan="7">{{ goal.get_frequency_display() }}</td></tr>
            {% endif %}
            <tr class="{{ loop.cycle("even", "odd") }}">
                <td class="goalTitle" data-goal-id="{{ goal.id }}" data-goal-name="{{ goal.name }}">
                    <span class="name">{{ goal.name }}</span>
                    <span class="delete"><img src="/static/img/delete.png" width="16" height="16"></span>
                </td>
                {% for date in goal.get_trailing_dates() -%}
                    <td class="trackBox {{"current" if loop.last else "subtle" }}" data-goal-id="{{ goal.id }}" data-goal-date="{{ date }}">
                    <div class="date">{{ render_date(date, goal.frequency) }}</div>
                    <div class="checkWrapper">{% for i in range(goal.get_date_count(date)) -%}
                        <div class="check"></div>
                    {%- endfor %}</div></td>
                {%- endfor %}
        {% endfor %}
    </table>
    <div id='new_goal'>
        <form action='#'>
            <div>
                Goal<br/>
                <input type='text' name='name'>
            </div>
            <div>
                Frequency<br/>
                <select name='frequency'>
                    <option value='1'>Daily</option>
                    <option value='2'>Weekly</option>
                    <option value='3'>Monthly</option>
                    <option value='4'>Yearly</option>
                </select>
            </div>
            <div id='buttons'>
                <input type='submit' value='Create'>
                <input type='button' value='Cancel'>
            </div>
        </form>
    </div>
{% endblock %}
{% block after_container %}
    {% if not request.user.is_authenticated() %}
        <div class="container-narrow">
            <div class="subheaders clearfix">
                <div>
                    <h2>Set Goals</h2>
                    <p>Define your own timeframe. Create goals that you want to accomplish on a daily, weekly, monthly, or even yearly basis.</p>
                </div>
                <div>
                    <h2>Achieve Them</h2>
                    <p>Just click the date to check off your goal! The neat retrospective layout shows you when you're all caught up.</p>
                </div>
                <div>
                    <h2>Be Happy :)</h2>
                    <p>You did it! Now go take a nap or something.</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

website/goals/templates/login.jinja
{% extends "base.jinja" %}
{% block extra_css %}
<style type="text/css">
    a.forgot {
        font-size: 0.8em;
    }
</style>
{% endblock %}
{% block inner_header %}Login{% endblock %}
{% block body_class %}login{% endblock %}
{% block content %}
    <p class="text-error">{{ error_msg }}</p>
    <form class="form-inline" action="{% url login %}" method="post">
        {% csrf_token %}
        <input type="email" autocorrect="off" autocapitalize="off" class="input-large" name="email" placeholder="Email" autofocus="autofocus">
        <input type="password" class="input-medium" name="password" placeholder="Password">
        {#<label class="checkbox">
            <input type="checkbox"> Remember me
        </label>#}
        <button type="submit" class="btn">Sign in</button>
        <a class="forgot" href="{% url password_reset %}">forgot password?</a>
    </form>
{% endblock %}

website/goals/templates/password_reset_complete.html
{% block content %}

<h1>Password reset complete</h1>

<p>Your password has been set.  You may go ahead and log in now.</p>

<p><a href="{{ login_url }}">Log in</a></p>

{% endblock %}

website/goals/templates/password_reset_confirm.html
{% block content %}

{% if validlink %}

<h1>Enter new password</h1>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form action="" method="post">{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">New password:</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">Confirm password:</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="Change my password" /></p>
</form>

{% else %}

<h1>Password reset unsuccessful</h1>

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}

{% endblock %}

website/goals/templates/password_reset_email.html
You're receiving this e-mail because you requested a password reset
for your user account at {{ site_name|safe }} <{{ domain }}>.

Your username, in case you've forgotten: {{ user.username }}

Please go to the following page and choose a new password:
{% block reset_link %}
    {{ domain }}{% url django.contrib.auth.views.password_reset_confirm uidb36=uid token=token %}
{% endblock %}

Thanks for using {{ site_name|safe }}!

website/goals/templates/password_reset_form.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>Password reset</h1>
    <p style="width:600px;">
        Forgotten your username or password?
    </p>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        {{ form.email.errors|safe }}
        <p><label for="id_email"><strong>Enter your e-mail address:</strong></label> {{ form.email|safe }} <input type="submit" value="Reset my password" /></p>
    </form>
{% endblock %}

website/goals/templates/signup.jinja
{% extends "base.jinja" %}
{% block inner_header %}Signup{% endblock %}
{% block body_class %}signup{% endblock %}
{% block content %}
    <p class="text-error">{{ error_msg }}</p>
    <form class="form-horizontal" action="{% url signup %}" method="post">
      {% csrf_token %}
      <div class="control-group">
        <label class="control-label" for="inputEmail">Email:</label>
        <div class="controls">
          <input class="input-xlarge" name="email" type="email" autocorrect="off" autocapitalize="off" id="inputEmail" placeholder="Email" autofocus="autofocus">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputPassword">Password:</label>
        <div class="controls">
          <input class="input-xlarge" name="password" type="password" id="inputPassword" placeholder="Password">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
          <button type="submit" class="btn">Sign Up</button>
        </div>
      </div>
    </form>
{% endblock %}

website/goals/templates/totals.jinja
{% extends "base.jinja" %}
{% block content %}
<table id="totals">
<tr><th>Date</th><th style='text-align:right;'>Count</th></tr>
{% for total in totals %}
<tr><td>{{total.date}}</td><td style='text-align:right;'>{{total.count}}</td></tr>
{% endfor %}
</table>
{% endblock %}